project:
  type: website

website:
  title: "Sustainable DataHub"
  open-graph: true
  twitter-card: true
  favicon: Logo.png
  site-url: https://www.sustainabledatahub.com
  navbar:
    right:
      - about.qmd
      - book_club.qmd
      - icon: github
        text: Github
        href: https://github.com/alv-garcia
      - icon: linkedin
        text: Linkedin
        href: https://www.linkedin.com/in/alvaro-silveira-62a770176/
format:
  html:
    theme: theme.scss
    #css: styles.css

editor: visual

comments:
  giscus:
    repo: alv-garc/Alvaro_Garcia